import axios from 'axios';

const API_URL = 'http://localhost:3000/api';

async function testProjects() {
  console.log('Starting Projects API Verification...');
  try {
     // 1. Login to get token
    console.log('Attempting to login as admin...');
    const loginRes = await axios.post(`${API_URL}/auth/login`, {
      email: 'admin@ngo.com', // Using the credentials from Login.tsx demo
      password: 'admin123'
    });
    
    if (loginRes.status === 200 && loginRes.data.token) {
        console.log('✅ Login Successful');
    } else {
        console.error('❌ Login Failed', loginRes.status, loginRes.data);
        return;
    }

    const token = loginRes.data.token;

    // 2. Get Projects
    console.log('Fetching projects...');
    const res = await axios.get(`${API_URL}/projects`, {
      headers: { Authorization: `Bearer ${token}` }
    });
    
    if (res.status === 200) {
        console.log(`✅ Get Projects Success: Found ${res.data.length} projects`);
        if (res.data.length > 0) {
            console.log('Sample Project:', JSON.stringify(res.data[0], null, 2));
        }
    } else {
        console.error('❌ Get Projects Failed', res.status);
    }

    // 3. Create a Test Project (Optional, but good to verify)
    console.log('Creating a test project...');
    const testProject = {
        name: `Integration Test Project ${Date.now()}`,
        description: 'Auto-generated by verification script',
        start_date: new Date().toISOString().split('T')[0],
        end_date: new Date(Date.now() + 86400000 * 30).toISOString().split('T')[0],
        assigned_manager_id: loginRes.data.user.user_id // Assign self if admin/manager or pick one if needed. Admin can assign.
        // wait, assigned_manager_id needs to be a valid manager. Admin can probably assign anyone or themselves.
        // Let's first get a manager to assign to.
    };

    // fetch managers to find a valid ID
    const managersRes = await axios.get(`${API_URL}/users/managers`, {
        headers: { Authorization: `Bearer ${token}` }
    });
    
    if (managersRes.data.length > 0) {
        testProject.assigned_manager_id = managersRes.data[0].user_id;
        console.log(`Assigning to manager ID: ${testProject.assigned_manager_id}`);
        
        const createRes = await axios.post(`${API_URL}/projects`, testProject, {
            headers: { Authorization: `Bearer ${token}` }
        });

        if (createRes.status === 201) {
             console.log('✅ Create Project Success');
             console.log('New Project ID:', createRes.data.project.insertId || createRes.data.project.project_id);
        } else {
             console.error('❌ Create Project Failed', createRes.status, createRes.data);
        }

    } else {
        console.warn('⚠️ No managers found to assign project to. Skipping create test.');
    }

  } catch (error) {
    console.error('❌ Projects Test Failed:', error.response?.data || error.message);
  }
}

testProjects();
